<?php


$lang = array (
//main
'version'		=> 'Vinaget 3.2.6',
'homepage'		=> 'FrenchDebrid.eu',
'title'		=> ' > MrBLAKEN is Here !',
'login'		=> '  ',
'password'		=> 'Password :',
'plugins'		=> 'Plugins',
'premium'		=> 'Premium Accounts :',
'moreacc'		=> 'More accounts >>>',
'lessacc'		=> '<<< Less accounts',
'main'		=> 'Main Window',
'donate'		=> 'Donate Acc',
'listfile'		=> 'Server Files',
'check'		=> 'Check Acc',
'log'		=> 'Log Out',
'welcome'		=> '<font color=#FF0000><B><font color=white>%s</font> > MrBLAKEN is Here !</B></font>',
'maxline'		=> '  ',
'example'		=> '<SPAN style="FONT-FAMILY: Arial; COLOR: #FFFFFF; FONT-SIZE: 10px">  </SPAN>',
'sbdown'		=> 'Download',
'dlhere'		=> 'Download here:',

// donate 
'donations'		=> '<font color=#FF3300>We are also in need of donations! If you can we would appreciate your offerings.<br/>Donate your Account !</font>',
'acctype'		=> 'Account Type:',
'sbdonate'		=> 'Donate Account',
'invalid'		=> '<font color=red><b>Invalid account. Please re-check your data!</b></font>',
'success'		=> '<font color=#FF3300>Thanks for donating your account. Your account has been created successfully our database.</font>',
'dsuccess'		=> '<img src="images/success.png"><BR><b><font color=#86a5d5>Donate Success!</font></b>',
'getloading'		=> '<img src="images/loading.gif"><BR>checking...',
'notaccess'		=> '<b>403 Page Not Found !</b>',

//check

//notice
'notice'		=> '',
'yourjobs'		=> 'Your IP: %s . Vos Lien Debridez: %s . ',
'status'		=> 'Limit par Fichier: %s. Total liens Debridez: %s .',

//time 

'ago'		=> 'ago',
'days'		=> 'days',
'hours'		=> 'hours',
'mins'		=> 'mins',
'sec'		=> 'sec',


//down
'errorget'		=> '&#9734; Problem During Leeching ! Please Retry Later ! &#9734;',
'errordl'		=> '&#9734; Your link has been generated by another ip address ! &#9734;',
'erroracc'		=> '<font color=red>&#9734; Account/Cookie Error !!! &#9734;</font>',
'svload'		=> '&#9734; Server Is Overloaded ! Retry Later ! &#9734;',
'issex'		=> '<B><font color=red>is this link sex ??? ==&#9658;</font> <a href=http://www.google.com/search?q=%s><font color=#00CC00>%s</font></a><br/><font color=#FFCC00>if not ==&#9658; Repost:</font> <font color=#0066CC>%s</font><font color=#FF3300>|</font><font color=#ff9999 face=Arial>not3x</font></b><BR>',
'errorlink'		=> '&#9734; Your Link Is Invalid !',
'manyjob'		=> '&#9734; Too many download ! Retry Tomorrow &#9734;',
'countMBIP'		=> '<center><b><i><font color=red>You only can download %s per %s ! Please wait <font color=green size=4>%s</font></font></i></b></center>',
'limitPERIP'		=> '<center><b><i><font color=red>You only can download %s file per %s ! Please wait <font color=green size=4>%s</font></font></i></b></center>',
'limitip'		=> 'Too many download jobs for this ip.',
'notsupport'		=> '<b><a href=%s style=\'TEXT-DECORATION: none\'><font color=red face=Arial size=2>%s</font></a>  <font color=#000000 face=Arial size=2>&#9734; Your Link Is Dead ! Or We Get Error During Leeching , Retry Later !</font></b><BR>',
'notdl'		=> '<b><a id=\'notsupport\' href=%s style=\'TEXT-DECORATION: none\'><font color=#ffcc33 face=Arial size=2>%s</font></a></b> <font color=red>&#9734; Problem During Leeching ! Retry Later ...</font><BR>',
'cantjob'		=> '<center><b><i><font color=red>Can not create new job</font></i></b></center>',
'filebig'		=> '<center><b><font color=#00CC00>%s</font> <font color=red>%s &#9734; Your File Is Too Big ! </font><font color=#3399FF>We Only Allowed </font> <font color=#FFCC00>%s</font></b></center>',

//Server Files
'notfound'		=> 'Not Found!',
'del'		=> 'Delete',
'rname'		=> 'Rename',
'notfile'		=> 'No Files Found',
'acdis'		=> 'Action Disabled',
'ac'		=> 'Action',
'name'		=> 'Name',
'size'		=> 'Size',
'date'		=> 'Date',
'original'		=> 'Original Link',
'clickcheck'		=> 'Click here to check link',
'total'		=> 'Total',
'used'		=> 'You used',
'reset'		=> 'Reset per',
'canl'		=> 'Cancel',
'deld'		=> 'Deleted!',
'nname'		=> 'New Name',
'bname'		=> 'You can\'t rename file to blank name!',
'rnameto'		=> 'renamed to',

//report
'dead'		=> '&#9734; Your Link Is Dead !  &#9734;',
'again'		=> '==&#9658; please try again',
'notwork'		=> '==&#9658; Acc not work',
'unavailable'		=> '&#9734; Service Temporary Unavailable &#9734;',
'disabletrial'		=> 'your link is temporary disable for trial account.',
'adult'		=> 'Adult Video Detected',
'ytb_captcha'		=> 'Captcha Found. Please run on different server',
'ytb_Error'		=> 'Error Locating Downlod URL',
'reportpass'		=> '<CENTER>The file you are trying to download is password protected. Please enter the password below.</CENTER>',
'outofbw'		=> '<font color=red>Account out of bandwidth !!!</font>',

);
?>